### ISSUE TITLE
Sturcture of model

### ISSUE THREAD

**Issue by wxlsummer** [lkytal/PredFull#2]
您好
我是爱丁堡大学人工智能专业今年的硕士毕业生。
我今年的毕业设计项目和您的这个项目很相似。我想复现一下您的CNN的结构，所以我能不能看看您的模型的构建代码？
我的邮箱：s1905792@ed.ac.uk ，如果可以的话非常感谢~

**Comment by lkytal** [comment]
构建的具体代码我们还在整理, 会更晚一些放出来. 不过你可以先通过model.summary()的方法看到模型的结构, 总体而言都是基于通用的结构构建的, 谢谢

**Comment by lkytal** [comment]
See build_model_example.py file in this repo for the sample structure, thanks.
